# Generated by Django 6.0.6 on 2026-07-10 05:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('root', models.BigIntegerField(verbose_name='Внешний id страницы маркетплейса')),
                ('name', models.CharField(max_length=128, verbose_name='Название карточки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_products', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Niche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Имя ниши')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='niches', to=settings.AUTH_USER_MODEL)),
                ('products', models.ManyToManyField(to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nm', models.BigIntegerField()),
                ('name', models.CharField(max_length=128, verbose_name='Название карточки')),
                ('is_tracked', models.BooleanField(default=True)),
                ('is_alive', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='PriceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_id', models.BigIntegerField(verbose_name='Размер товара')),
                ('size_name', models.CharField(blank=True, default='', max_length=10, verbose_name='Размер')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='Цена товара')),
                ('basic_price', models.IntegerField(blank=True, null=True, verbose_name='Цена товара без скидки')),
                ('stock', models.IntegerField(verbose_name='Количество товара')),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='Рейтинг размера товара')),
                ('reviews_count', models.IntegerField(blank=True, null=True, verbose_name='Количество отзывов')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='products.productitem')),
            ],
        ),
        migrations.CreateModel(
            name='TelegramAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('user', 'root'), name='unique_user_root_product'),
        ),
        migrations.AddConstraint(
            model_name='niche',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_user_name'),
        ),
        migrations.AddConstraint(
            model_name='productitem',
            constraint=models.UniqueConstraint(fields=('product', 'nm'), name='unique_product_nm'),
        ),
        migrations.AddIndex(
            model_name='pricesnapshot',
            index=models.Index(fields=['item', 'option_id', 'created_at'], name='snapshot_item_opt_date_idx'),
        ),
        migrations.AddIndex(
            model_name='pricesnapshot',
            index=models.Index(fields=['item', 'created_at'], name='snapshot_item_date_idx'),
        ),
    ]
